### ISSUE TITLE
Re-add OpenSUSE data files

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-data#59]
A mistake I made a few months back zero-ed out the OpenSUSE files in this repository (they're still OK in production), so they need to be committed to this repository again fresh from the output of package_build.py.

**Comment by pleia2** [comment]
@aashish-khatri did you want to take a look at this one?

**Comment by aashish-khatri** [comment]
> @aashish-khatri did you want to take a look at this one?

Sure @pleia2, I'll take a look at this issue.

**Comment by rachejazz** [comment]
@pleia2 @aashish-khatri ~~just discovered the package_build.py isn't able to read data files from opensuse server. It can be that the source has been removed.~~
~~This issue can be better named as update opensuse data file source on script~~

on further debug, the regex that was used to take out package names has become outdated:
```
 71         else:
 72             ref_data = re.findall(r"<a href=\"(.*\.rpm)\"><img.*<\/a>", data)
 73             print(ref_data)
```

Before this line, requests module is able to pull the pkg names. I will fix this in few hours. Since this is a dependency of another SDT issue, this is high priority

**Comment by arshPratap** [comment]
- [x] #61
- [x] [**OpenSUSE Source Fix** ](https://github.com/openmainframeproject/software-discovery-tool/pull/156)
